name: arxiv
hf_dataset:
  _target_: datasets.load_dataset
  path: CShorten/ML-ArXiv-Papers
data_object:
  _target_: he_aware_training.dataset.streaming.StreamingDataset
  _recursive_: False
  dataset_cfg:
    _target_: datasets.load_dataset
    path: CShorten/ML-ArXiv-Papers
  tokenizer: ???
  split: ???
  model_name: ${model.name}