name: wikitext
hf_dataset:
  _target_: datasets.load_dataset
  name: wikitext-103-v1
  path: Salesforce/wikitext
data_object:
  _target_: he_aware_training.dataset.streaming.StreamingDataset
  _recursive_: False
  dataset_cfg:
    _target_: datasets.load_dataset
    name: wikitext-103-v1
    path: Salesforce/wikitext  
  tokenizer: ???
  split: ???
  model_name: ${model.name}